### PR TITLE
Update polo-fr.po

### PR DESCRIPTION
**Pull request by Fabeuss**
Full updated french translation.
Can you please merge the file and include it in a future update of Polo File Manager ?

Thanks, 

Fabeuss

### CODE REVIEW

**Comment by teejee2008** [comment]
Thanks

**Comment by DesmoricFR** [comment]
Hi, 
I installed Polo (v18.8.2) with the official "run" file on a manjaro linux pc. I'm asking why Polo is not fully translated in french ?

**Comment by Fabeuss** [comment]
Sorry, but it's been 4 years since the last translation. I haven't used polo since... Maybe you could translate what hasn't been translated yet?

**Comment by DesmoricFR** [comment]
> Sorry, but it's been 4 years since the last translation. I haven't used polo since... Maybe you could translate what hasn't been translated yet?

Yes, I can do that, but I don't know how. Is it a file to complete ?

**Comment by Fabeuss** [comment]
Yes you can fork this project and just change the file called "po/polo-fr.po" and pull it.

**Comment by Fabeuss** [comment]
Just hope that teejee2008 will update this old app with your changes 😉

**Comment by DesmoricFR** [comment]
> Yes you can fork this project and just change the file called "po/polo-fr.po" and pull it.

OK, I will do that as soon as possible.

**Comment by DesmoricFR** [comment]
> Just hope that teejee2008 will update this old app with your changes 😉

I hope so, too 👌

**Pull request merged**
